global:
  scrape_interval:     1s
  evaluation_interval: 1s

scrape_configs:
  - job_name: 'backend-metrics'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['backend:8080']